"use strict";

const path = require("path");
const nconf = require("nconf");
const winston = require("winston");

const dataToLoad = [
  // "AbuseReasons",
  // "AchievementCategories",
  // "AchievementObjectives",
  // "AchievementRewards",
  // "Achievements",
  // "ActionDescriptions",
  // "AlignmentBalance",
  // "AlignmentEffect",
  // "AlignmentGift",
  // "AlignmentOrder",
  // "AlignmentRank",
  // "AlignmentRankJntGift",
  // "AlignmentSides",
  // "AlignmentTitles",
  // "AlmanaxCalendars",
  // "Appearances",
  // "Areas",
  // "Bonuses",
  // "BonusesCriterions",
  // "BreedRoles",
  // "Breeds",
  // "CensoredContents",
  // "CensoredWords",
  // "Challenge",
  // "CharacteristicCategories",
  // "Characteristics",
  // "ChatChannels",
  // "Comics",
  // "CompanionCharacteristics",
  // "Companions",
  // "CompanionSpells",
  // "CreatureBonesOverrides",
  // "CreatureBonesTypes",
  // "DareCriterias",
  // "Documents",
  // "Dungeons",
  "Effects",
  // "EmblemBackgrounds",
  // "EmblemSymbolCategories",
  // "EmblemSymbols",
  // "Emoticons",
  // "ExternalNotifications",
  // "FinishMoves",
  // "HavenbagFurnitures",
  // "HavenbagThemes",
  // "Heads",
  // "HintCategory",
  // "Hints",
  // "Houses",
  // "Idols",
  // "IdolsPresetIcons",
  // "Incarnation",
  // "IncarnationLevels",
  // "InfoMessages",
  // "Interactives",
  "Items",
  // "ItemSets",
  "ItemTypes",
  "Jobs",
  // "LegendaryTreasureHunts",
  // "LivingObjectSkinJntMood",
  // "MapCoordinates",
  // "MapPositions",
  // "MapReferences",
  // "MapScrollActions",
  // "MonsterMiniBoss",
  // "MonsterRaces",
  // "Monsters",
  // "MonsterSuperRaces",
  // "Months",
  // "MountBehaviors",
  // "MountBones",
  // "MountFamily",
  // "Mounts",
  // "NamingRules",
  // "Notifications",
  // "NpcActions",
  // "NpcMessages",
  // "Npcs",
  // "OptionalFeatures",
  // "Ornaments",
  // "Pack",
  // "Pets",
  // "Phoenixes",
  // "Playlists",
  // "PointOfInterest",
  // "PointOfInterestCategory",
  // "PresetIcons",
  // "QuestCategory",
  // "QuestObjectives",
  // "QuestObjectiveTypes",
  // "Quests",
  // "QuestStepRewards",
  // "QuestSteps",
  // "RankNames",
  "Recipes",
  // "RideFood",
  // "ServerCommunities",
  // "ServerGameTypes",
  // "ServerLangs",
  // "ServerPopulations",
  // "Servers",
  // "SkillNames",
  // "Skills",
  // "SkinMappings",
  // "SkinPositions",
  // "SmileyCategories",
  // "SmileyPacks",
  // "Smileys",
  // "SoundBones",
  // "SoundUi",
  // "SoundUiHook",
  // "SpeakingItemsText",
  // "SpeakingItemsTriggers",
  // "SpellBombs",
  // "SpellLevels",
  // "SpellPairs",
  // "Spells",
  "SpellStates",
  // "SpellTypes",
  // "StealthBones",
  // "SubAreas",
  // "SuperAreas",
  // "TaxCollectorFirstnames",
  // "TaxCollectorNames",
  // "Tips",
  // "TitleCategories",
  // "Titles",
  // "TypeActions",
  // "Url",
  // "VeteranRewards",
  // "Waypoints",
  // "WorldMaps",
];

const dataPath = path.resolve(process.cwd(), nconf.get("dataPath"));
winston.info(`Loading from ${dataPath}`);
const makePath = file => path.join(dataPath, `${file}.json`);

dataToLoad.forEach(data => {
  exports[data] = require(`${makePath(data)}`); // eslint-disable-line
});
